#!/usr/bin/env bash

# PROVIDE: pms

. /etc/rc.subr

name="jackett"
rcvar=`set_rcvar`
start_cmd="${name}_start"
stop_cmd="${name}_stop"
update_cmd="${name}_update"
extra_commands="update"

load_rc_config $name

jackett_start()
{
    if checkyesno ${rcvar}; then
      echo "Starting jackett"
      service jackett_old start
    fi
}
jackett_stop()
{
    if checkyesno ${rcvar}; then
      echo "Stopping jackett"
      service jackett_old stop
    fi
}
jackett_update()
{
    if checkyesno ${rcvar}; then
      echo "Finding latest jackett version"
      fetch -o releases.json https://api.github.com/repos/Jackett/Jackett/releases
      download_url=$(cat releases.json | jq -r '[.[] | select(.prerelease==false)][0] | [.assets[] | select(.name="Jackett.Binaries.LinuxAMDx64.tar.gz")][0] | .browser_download_url')
      version=$(cat releases.json | jq -r '[.[] | select(.prerelease==false)][0] | .name')
      rm releases.json

      echo "Downloading jackett version: ${version}"
      fetch "${download_url}"

      jackett_stop
      echo "Updating current jackett"
      rm -rf Jackett
      tar xzf "Jackett.Binaries.LinuxAMDx64.tar.gz"
      rm -rf /usr/local/share/jackett_old
      mv /usr/local/share/jackett /usr/local/share/jackett_old
      mv "./Jackett" /usr/local/share/jackett
      #rm "Jackett.Binaries.LinuxAMDx64.tar.gz"
      jackett_start
    fi
}

run_rc_command "$1"
